---
version: '2'

volumes:
  orderer1.example.com:
  orderer2.example.com:
  orderer3.example.com:

networks:
  blockchain:
    external: true

services:
  orderer1.example.com:
    container_name: orderer1.example.com
    extends:
      file: base/orderer-base.yaml
      service: orderer-base
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer1.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - blockchain
    # orderer节点地址
    extra_hosts:
      - orderer1.example.com:10.211.55.10
      - orderer2.example.com:10.211.55.10
      - orderer3.example.com:10.211.55.10

  orderer2.example.com:
    container_name: orderer2.example.com
    extends:
      file: base/orderer-base.yaml
      service: orderer-base
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer2.example.com:/var/hyperledger/production/orderer
    ports:
      - 8050:7050
    networks:
      - blockchain
    # orderer节点地址
    extra_hosts:
      - orderer1.example.com:10.211.55.10
      - orderer2.example.com:10.211.55.10
      - orderer3.example.com:10.211.55.10

  orderer3.example.com:
    container_name: orderer3.example.com
    extends:
      file: base/orderer-base.yaml
      service: orderer-base
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/:/var/hyperledger/orderer/tls
        - orderer3.example.com:/var/hyperledger/production/orderer
    ports:
      - 9050:7050
    networks:
      - blockchain
    # orderer节点地址
    extra_hosts:
      - orderer1.example.com:10.211.55.10
      - orderer2.example.com:10.211.55.10
      - orderer3.example.com:10.211.55.10
